frase='Feliz Aniversario'
print(frase[9])
print(frase[6:17])
print(frase[:22])
print(frase[:22:2])
print(frase[5:])
print(frase[5::2])
print(len(frase))
print(frase.count('a'))
print(frase.count('a', 0, 14))
print(frase.find('io'))
print('feliz' in frase)
print(frase.replace('Aniversario','Ano Novo'))
print(frase.upper())
print(frase.lower())
print(frase.captalize())
print(frase.title())
print(frase.split())
print('-'.join(frase))